config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    # flash[:notice] = "Signed in successfully"
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully"
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_inactive_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(resource)
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  
  def index
    #index部分
    @books = Book.all

    #new部分
    @book = Book.new

    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      render :index
    end
  end

  def show
    @book1 = Book.find(params[:id])
    @book2 = Book.new
    @user = @book1.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to books_path unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
    <h2>User info</h2>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

    </div>
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
    <div class="form-group">
      <label>Title</label><br>
        <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label>Opinion</label><br>
        <%= f.text_area :body %>
    </div>
      <%= f.submit 'Create Book', class:"btn btn-success" %>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibitied this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @book do |f| %>

      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Opinion</h4>
      <%= f.text_area :body %><br>

      <%= f.submit 'Update Book', class:"btn btn-success" %><br>

      <%= link_to "Show", book_path(@book.id) %>|<%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibitied this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <%= render 'list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="5"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td><%= link_to "#{book.title}",book_path(book.id) %></td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
            <% end %>
            <td><%= "コメント数:#{book.book_comments.count}" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'list', user: @user, book: @book2 %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
            <%= link_to user_path(@book1.user.id) do %>
              <%= image_tag @book1.user.get_profile_image(100,100) %><br><%= @book1.user.name %>
            <% end %>
            </td>
            <td><%= link_to "#{@book1.title}", book_path(@book1.id) %></td>
            <td><%= @book1.body %></td>
            <% if @book1.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(@book1), method: :delete do %>
                  <i class="fas fa-heart"></i><%= @book1.favorites.count %>
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(@book1), method: :post do %>
                  <i class="fas fa-heart"></i><%= @book1.favorites.count %>
                <% end %>
              </td>
            <% end %>
            <td><%= "コメント数：#{@book1.book_comments.count}" %></td>
            <% if @book1.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book1.id), class:"btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book1), method: :delete, "data-confirm"=> "本当に消しますか？", class:"btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <tbody>
          <tr>
            <% @book1.book_comments.each do |book_comment| %>
            <td>
            <%= link_to user_path(book_comment.user.id) do %>
              <%= image_tag book_comment.user.get_profile_image(100,100) %><br><%= book_comment.user.name %>
            <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <% if book_comment.user == current_user %>
              <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-sm btn-danger" %></td>
            <% end %>
          <% end %>
          </tr>
        </tbody>
      </table>
      <div>
        <%= form_with model:[@book1, @book_comment] do |f| %>
          <%= f.text_area :comment, rows:'5' %><br>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class:"nav-link text-light" do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <a class="nav-link text-light" href="/books">
                <i class="fas fa-book-open"></i> Books
              </a>
            </li>
            <li>
              <a class="nav-link text-light" data-method="delete" href="/users/sign_out">
                <i class="fas fa-sign-out-alt"></i> logout
              </a>
            </li>
            <% else %>
            <li>
              <a class="nav-link text-light" href="/">
                <i class="fas fa-home"></i> Home
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/home/about">
                <i class="fas fa-link"></i> About
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/users/sign_up">
                <i class="fas fa-user-plus"></i> sign up
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/users/sign_in">
                <i class="fas fa-sign-in-alt"></i> login
              </a>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p class="notice"><%= flash[:notice] %></p>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %> errors prohibitied this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label><br>
          <%= f.text_field :name, autofocus: true, id:"inputName"%>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label><br>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label><br>
          <%= f.text_area :introduction, autofocus: true, id:"user_introduction" %>
        </div>
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>iamge</th>
            <th>name</th>
            <th cospan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="5"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
            <% end %>
            <td><%=  "コメント数：#{book.book_comments.count}" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>